apiVersion: v1
kind: PersistentVolume
metadata:
  name: siddhi-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: <SERVER_IP>
    path: <PATH>