apiVersion: siddhi.io/v1alpha2
kind: SiddhiProcess
metadata: 
  name: nats-app
spec: 
  apps: 
    - script: |
        @App:name("MonitorApp")
        @App:description("Description of the plan") 
  
        @source(
            type='http',
            receiver.url='${RECEIVER_URL}',
            basic.auth.enabled='${BASIC_AUTH_ENABLED}',
            @map(type='json')
        )
        define stream DevicePowerStream (type string, deviceID string, power int);
        
        @sink(type='log', prefix='LOGGER')
        define stream MonitorDevicesPowerStream(sumPower long);
        @info(name='monitored-filter')
        from DevicePowerStream#window.time(100 min)
        select sum(power) as sumPower
        insert all events into MonitorDevicesPowerStream;

  container: 
    env: 
      - 
        name: RECEIVER_URL
        value: "http://0.0.0.0:8080/example"
      - 
        name: BASIC_AUTH_ENABLED
        value: "false"
    image: "siddhiio/siddhi-runner-ubuntu:5.1.0"
  
  messagingSystem: 
    config: 
      bootstrap.servers: 
        - "nats://siddhi-nats:4222"
      cluster.id: siddhi-stan
    type: nats
  
  persistentVolume: 
    access.modes: 
      - ReadWriteOnce
    resources: 
      requests: 
        storage: 1Gi
    storageClassName: standard
    volume.mode: Filesystem
  
  runner: |
    state.persistence:
      enabled: true
      intervalInMin: 1
      revisionsToKeep: 2
      persistenceStore: io.siddhi.distribution.core.persistence.FileSystemPersistenceStore
      config:
        location: siddhi-app-persistence
