apiVersion: siddhi.io/v1alpha2
kind: SiddhiProcess
metadata: 
  name: nats-app
spec: 
  apps: 
    - script: |
        @App:name("MonitorApp")
        @App:description("Description of the plan") 
  
        @source(
            type='http',
            receiver.url='${RECEIVER_URL}',
            basic.auth.enabled='${BASIC_AUTH_ENABLED}',
            @map(type='json')
        )
        define stream DevicePowerStream (type string, deviceID string, power int);
        
        @sink(type='log', prefix='LOGGER')	
        define stream MonitorDevicesPowerStream(deviceID string, power int);	
          
        @info(name='monitored-filter')	
        from DevicePowerStream[type == 'monitored']	
        select deviceID, power	
        insert into MonitorDevicesPowerStream;

  container: 
    env: 
      - 
        name: RECEIVER_URL
        value: "http://0.0.0.0:8080/example"
      - 
        name: BASIC_AUTH_ENABLED
        value: "false"
    image: "siddhiio/siddhi-runner-ubuntu:5.1.0"
  imagePullSecret: siddhi

  runner: |
    state.persistence:
      enabled: true
      intervalInMin: 1
      revisionsToKeep: 2
      persistenceStore: io.siddhi.distribution.core.persistence.FileSystemPersistenceStore
      config:
        location: siddhi-app-persistence
